"""
Standard Charts Module - TR Chart Generator v4.0
Generates Line, Candlestick, and OHLC charts with volume and RSI
Uses TradingView widgets for professional, interactive charts
"""

import os
import webbrowser
from datetime import datetime


class StandardCharts:
    """Generate standard technical analysis charts using TradingView widgets"""
    
    def __init__(self, output_dir='charts'):
        """Initialize with output directory"""
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
    
    def generate_tradingview_chart(self, ticker, chart_type='candlestick', 
                                   interval='D', studies=None):
        """
        Generate TradingView embedded chart
        
        Args:
            ticker (str): Stock symbol
            chart_type (str): 'line', 'candlestick', 'bars' (OHLC)
            interval (str): 'D' (daily), 'W' (weekly), 'M' (monthly)
            studies (list): Technical indicators like ['RSI', 'Volume']
        
        Returns:
            str: Path to generated HTML file
        """
        if studies is None:
            studies = ['RSI@tv-basicstudies', 'Volume@tv-basicstudies']
        
        # Map our chart types to TradingView types
        tv_chart_types = {
            'line': 2,           # Line chart
            'candlestick': 1,    # Candlestick chart
            'ohlc': 0,           # Bars (OHLC)
            'bars': 0            # Alias for OHLC
        }
        
        chart_style = tv_chart_types.get(chart_type.lower(), 1)
        
        # TradingView widget HTML
        html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{ticker} - {chart_type.title()} Chart</title>
    <style>
        body {{
            margin: 0;
            padding: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background-color: #131722;
        }}
        .header {{
            background-color: #1E222D;
            color: white;
            padding: 20px;
            text-align: center;
            border-bottom: 1px solid #2A2E39;
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
            font-weight: 600;
        }}
        .header p {{
            margin: 5px 0 0 0;
            color: #787B86;
            font-size: 14px;
        }}
        .chart-container {{
            height: calc(100vh - 100px);
            width: 100%;
        }}
        .footer {{
            background-color: #1E222D;
            color: #787B86;
            padding: 10px;
            text-align: center;
            font-size: 12px;
            border-top: 1px solid #2A2E39;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{ticker} - {chart_type.title()} Chart</h1>
        <p>Generated by TR Chart Generator v4.0 | {datetime.now().strftime('%B %d, %Y')}</p>
    </div>
    
    <div class="chart-container">
        <!-- TradingView Widget BEGIN -->
        <div class="tradingview-widget-container" style="height:100%;width:100%">
          <div class="tradingview-widget-container__widget" style="height:calc(100% - 32px);width:100%"></div>
          <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js" async>
          {{
            "autosize": true,
            "symbol": "{ticker}",
            "interval": "{interval}",
            "timezone": "America/New_York",
            "theme": "dark",
            "style": "{chart_style}",
            "locale": "en",
            "enable_publishing": false,
            "allow_symbol_change": false,
            "studies": {studies},
            "support_host": "https://www.tradingview.com"
          }}
          </script>
        </div>
        <!-- TradingView Widget END -->
    </div>
    
    <div class="footer">
        Powered by TradingView | MJ Software LLC
    </div>
</body>
</html>
        """
        
        # Save HTML file
        filename = f"{ticker}_{chart_type.title()}_{interval}_TradingView.html"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(html_content)
        
        print(f"✅ Generated: {filename}")
        return filepath
    
    def generate_line_chart(self, ticker, interval='D'):
        """Generate line chart with volume and RSI"""
        print(f"\n📈 Generating Line Chart for {ticker}...")
        filepath = self.generate_tradingview_chart(
            ticker=ticker,
            chart_type='line',
            interval=interval,
            studies=['RSI@tv-basicstudies', 'Volume@tv-basicstudies']
        )
        return filepath
    
    def generate_candlestick_chart(self, ticker, interval='D'):
        """Generate candlestick chart with volume and RSI"""
        print(f"\n🕯️ Generating Candlestick Chart for {ticker}...")
        filepath = self.generate_tradingview_chart(
            ticker=ticker,
            chart_type='candlestick',
            interval=interval,
            studies=['RSI@tv-basicstudies', 'Volume@tv-basicstudies']
        )
        return filepath
    
    def generate_ohlc_chart(self, ticker, interval='D'):
        """Generate OHLC (bars) chart with volume and RSI"""
        print(f"\n📊 Generating OHLC Chart for {ticker}...")
        filepath = self.generate_tradingview_chart(
            ticker=ticker,
            chart_type='ohlc',
            interval=interval,
            studies=['RSI@tv-basicstudies', 'Volume@tv-basicstudies']
        )
        return filepath
    
    def generate_all_charts(self, ticker, interval='D', open_browser=True):
        """
        Generate all three chart types for a ticker
        
        Args:
            ticker (str): Stock symbol
            interval (str): Time interval ('D', 'W', 'M')
            open_browser (bool): Whether to open charts in browser
        
        Returns:
            dict: Paths to all generated charts
        """
        print(f"\n{'='*60}")
        print(f"🎨 GENERATING ALL STANDARD CHARTS FOR {ticker}")
        print(f"{'='*60}")
        
        charts = {}
        
        # Generate each chart type
        charts['line'] = self.generate_line_chart(ticker, interval)
        charts['candlestick'] = self.generate_candlestick_chart(ticker, interval)
        charts['ohlc'] = self.generate_ohlc_chart(ticker, interval)
        
        print(f"\n✅ All charts generated successfully!")
        print(f"📁 Location: {self.output_dir}/")
        
        # Open in browser if requested
        if open_browser:
            print(f"\n🌐 Opening charts in your browser...")
            for chart_type, filepath in charts.items():
                webbrowser.open('file://' + os.path.abspath(filepath))
        
        return charts
    
    def interactive_menu(self):
        """Interactive menu for generating charts"""
        while True:
            print(f"\n{'='*60}")
            print("STANDARD CHARTS GENERATOR")
            print(f"{'='*60}")
            print("1. Generate Line Chart")
            print("2. Generate Candlestick Chart")
            print("3. Generate OHLC Chart")
            print("4. Generate All Charts")
            print("0. Back to Main Menu")
            print(f"{'='*60}")
            
            choice = input("\nEnter your choice: ").strip()
            
            if choice == '0':
                break
            
            if choice not in ['1', '2', '3', '4']:
                print("❌ Invalid choice. Please try again.")
                continue
            
            # Get ticker
            ticker = input("\nEnter stock symbol (e.g., AAPL): ").strip().upper()
            if not ticker:
                print("❌ Invalid ticker symbol.")
                continue
            
            # Get interval
            print("\nSelect interval:")
            print("1. Daily (D)")
            print("2. Weekly (W)")
            print("3. Monthly (M)")
            interval_choice = input("Enter choice (default: Daily): ").strip() or '1'
            
            interval_map = {'1': 'D', '2': 'W', '3': 'M'}
            interval = interval_map.get(interval_choice, 'D')
            
            # Generate charts
            try:
                if choice == '1':
                    filepath = self.generate_line_chart(ticker, interval)
                    webbrowser.open('file://' + os.path.abspath(filepath))
                
                elif choice == '2':
                    filepath = self.generate_candlestick_chart(ticker, interval)
                    webbrowser.open('file://' + os.path.abspath(filepath))
                
                elif choice == '3':
                    filepath = self.generate_ohlc_chart(ticker, interval)
                    webbrowser.open('file://' + os.path.abspath(filepath))
                
                elif choice == '4':
                    self.generate_all_charts(ticker, interval, open_browser=True)
                
                print("\n✅ Chart generated and opened in browser!")
                print(f"📁 Saved to: {self.output_dir}/")
                
            except Exception as e:
                print(f"\n❌ Error generating chart: {str(e)}")
                continue


# Test function
def test_standard_charts():
    """Test the standard charts module"""
    print("Testing Standard Charts Module...")
    
    charts = StandardCharts()
    
    # Test with AAPL
    charts.generate_all_charts('AAPL', interval='D', open_browser=True)
    
    print("\n✅ Test complete!")


if __name__ == "__main__":
    # If run directly, show interactive menu
    charts = StandardCharts()
    charts.interactive_menu()
